### ISSUE TITLE
Is Python faster than R?

### ISSUE THREAD

**Issue by yogat3ch** [JoosKorstanje/outil_pms2#1]
Hi Joos,
I just read the article [Is Python faster than R?](https://towardsdatascience.com/is-python-faster-than-r-db06c5be5ce8).

I tried to find a more direct way to get in touch with you, but your website doesn't have a form with which to email you, it doesn't appear to be possible to message you via Medium, I would have to request a connection on LinkedIn to message you, and I couldn't find the repo for the code you used in the Medium article on this Github, so this was the most direct way I could come up with to contact you.

I wanted to let you know that by omitting the `repeats` argument to `trainControl`, you're running 5-fold CV twice, rather than once since `repeats` defaults to `1` when `method = 'cv'`.
You can verify this by checking the docs for `trainControl` by typing `?caret::trainControl` at the console. As it stands, the code is training each model twice in R for each one time that you train it in Python. Set `repeats = 0` and it will resolve this issue. 

Furthermore, if you're running a Mac of any kind, the default parallel processing backend is Mac's 'fork' process feature which is far faster than using the 'PSOCK' method. Windows users have to use this method since Windows doesn't support forking, but given you're on a Mac I imagine the Python is using the `fork` method by default. You should be able to use `parallel::makeForkCluster` to ensure that both R and Python use the same parallel backend.

I'd be interested in checking out the article again once it's updated with the new results!

**Comment by JoosKorstanje** [comment]
Thanks for those points, I'll check them out as soon as I can!

**Comment by yogat3ch** [comment]
Awesome, thanks for the quick response! I guess this was a good way of getting in touch after all!
